# Generated by Django 4.1.7 on 2023-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('specializations', models.CharField(max_length=50)),
                ('doctorpic', models.FileField(default='anonymous.jpg', upload_to='media/')),
                ('contact', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
