# Generated by Django 4.2 on 2023-04-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0002_doctor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor_User',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
