# Generated by Django 4.1.7 on 2023-05-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0005_alter_doctor_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_user',
            name='descpic',
            field=models.FileField(default='anonymous.jpg', upload_to='media/'),
        ),
    ]
