# Generated by Django 4.1.7 on 2023-05-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0007_product_user_disease_user_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_user',
            name='productbenefit',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product_user',
            name='productdesc',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product_user',
            name='productqty',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
